name: Publish Docker
on: [create]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: aashish108/standardnotes-syncing-server/syncing-server-image:1.0
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        registry: docker.pkg.github.com  
